### ISSUE TITLE
Question Regarding Design Philosophy

### ISSUE THREAD

**Issue by einthusan** [RedDeadAlice/go-pong#1]
Hello,

Thanks for sharing this repo. I am hoping to learn some basic rendering stuff for our upcoming children's educational game.
I was hoping if you can give a little more details regarding your choices for this code design principle you have taken.
To be more clear, that are golang bindings for vulkan, glfw, and etc. but I see that you choose to write your renderer code in native C and the game logic in Golang. Why is that?

I was thinking of creating a more updated Golang binding for many of the C libraries that are of interest to me, but that requires using CGO, and at the moment, every golang binding packages seem to be "hacked" together and it seems Golang's support for C is not really that great as one would initially think. Hence, I am still debating if I should learn C and write the renderer in C as you have done, or attempt to create my own Go-bindings for vulkan, glm, gflw, and other C libraries.

Please suggest and share your thoughts. Thanks!

**Comment by Red1C3** [comment]
Hi,

As you've mentioned, there are Go bindings for a lot of C libraries out there, I did try OpenGL Go bindings in the past, and it was not a pleasant experience, most of the library was auto generated (you'll see some functions require unsafe pointers as parameters, some functions did not even work (maybe types issue)) with a couple of helper functions to ease the usage of the library, plus, every call to C  from Go is costly, so writing my own renderer reduced the calls from Go to C to a minimal, however, I'd like to mention that there are some 3D renderers written in Go (they rely on C under the hood), but they are Go friendly, they are not the same as using plain OpenGL or Vulkan, but they may be enough for your project, I used Go for game logic because I thought it would be better to use it for handling Websockets, if the game was meant to only be offline, I would have picked C++ for the whole project, so I think if you do not have a reason to use Go over C/C++, use C/C++, otherwise I'd recommend you to write your own renderer in C specifically for your project (writing bindings for whole libraries is time consuming, but it would be great if you do them imo), if learning C is not an option, you can check the available 3D engines around if they can do the job

**Comment by einthusan** [comment]
Thanks for the detailed feedback! I will attempt to write a bit of C code and learn, and if manageable will write my renderer in C and keep high-level access to Go. I enjoy writing in Go because its much more familiar for me, and i love the interface composition methods which is useful for gameplay inheritance logic. I always try to avoid C++ because I feel it maybe more difficult than C. I have been reading and writing some vulkan logic so I probably won't use a off-shelf game engine/renderer but of course use them as code examples.

Thanks and great code!
